[project]
name = "vc-boleto-digital-flet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flet-camera>=0.84.0",
    "flet>=0.84.0",
    "pillow>=12.2.0",
    "pyzbar>=0.1.9",
]

[dependency-groups]
dev = [
    "flet-cli>=0.85.0",
]

[tool.flet.app]
path = "src"

[tool.flet.android.permission]
"android.permission.CAMERA" = true
"android.permission.RECORD_AUDIO" = true

[tool.flet]
org = "com.example.boletodigital"
product = "boleto_digital"
permission = [
    "camera",
    "microphone",
]
